name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-n-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test

      - name: Clippy
        run: cargo clippy

      - name: Formatting
        run: cargo fmt --all -- --check
